### PR TITLE
Allow CLImate to be used as a PSR-3 logger

### PR DESCRIPTION
**Pull request by duncan3dc**
Inspired by #57 I created a simple `Logger` class that implements the PSR-3 LoggerInterface.

Including some of the other features from:
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md
* Objects with __toString()
* Exceptions in context
* Placeholders in context

### CODE REVIEW

**Comment by terah** [comment]
+1 on this

**Comment by terah** [comment]
Hi Craig,

Your $context handling in the Logger::log method doesn't support multi-dimensional arrays.  

I've also added a file writer: https://github.com/terah/climate/blob/master/src/Util/Writer/File.php.  I'm using it as so:

```php
   
    use League\CLImate;
  
    $file_handle = fopen('/path/to/my/log/file', 'a');
    $climate     = new CLImate\CLImate;
    $climate->output->add('logger', new \League\CLImate\Util\Writer\File($file_handle));
    $climate->output->defaultTo('logger');
    $myPsrLogger = new League\CLImate\Logger($climate);
```

**Comment by duncan3dc** [comment]
Ok, I've added recursive array support now, and a test for it.

That file writer should be submitted in a separate PR, nice work

**Comment by joetannenbaum** [comment]
@duncan3dc and @terah, thanks so much for your work on this. At this point, it definitely feels like a separate project with CLImate as a dependency, as opposed to adding a dependency of `psr/log` to CLImate just for this class.

@terah do you want to submit your file writer as a separate PR? It looks great, thank you.

**Comment by duncan3dc** [comment]
@joetannenbaum That makes sense. Would this project live in the league like other 'adapters'? Shall I propose it on the mailing list?

**Comment by duncan3dc** [comment]
I've thrown it up [here](https://github.com/duncan3dc/climate-logger) for now

**Pull request closed without merging**
