### PR TITLE
Fix error in accept() and defaultTo()

### PR DESCRIPTION
**Pull request by jasverix**
defaultTo() and accept() does not work together. Because the formatting is stored back into $this->acceptable, the default value is never accepted.

### CODE REVIEW

**Comment by jasverix** [comment]
Is there any maintainers still maintaing this project? This error is breaking, and the fix is very small and easy to implement.

**Comment by duncan3dc** [comment]
Hi @jasverix, all league projects are maintained, that's one of their benefits.
Is it possible for you to add a phpunit test for this fix? I'm sure that would make it easier for the maintainers to accept

**Comment by jasverix** [comment]
Thank you @duncan3dc. I added a test now to show the problem.

The thing is that the Input class is writing the results from acceptableItemFormatted back to $this->acceptable. $this->acceptable would then contain ['<bold>default</bold>', 'other] as an array. If i wrote 'default' or nothing, none of them would pass the acceptable test, and the prompt restarted. It was not possible to choose the default answer.

> What to you think? [<bold>y</bold>/n]
> What to you think? [<bold>y</bold>/n] y
> What to you think? [<bold>y</bold>/n] n
> Okay than...

**Comment by jasverix** [comment]
Looks like the HHVM tests is failing.

> HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.

But that does not have anything to do with this change.

**Comment by duncan3dc** [comment]
Thanks @jasverix, that looks great :+1:

**Pull request merged**
