### PR TITLE
Better check for Ansi color support on Linux.

### PR DESCRIPTION
**Pull request by azjezz**

### CODE REVIEW

**Comment by duncan3dc** [comment]
Hi @azjezz do you have any documentation regarding these changes? I'm happy to include them as long as we can verify where the logic comes from and whether it's officially supported behaviour or a workaround

**Comment by azjezz** [comment]
@duncan3dc see https://github.com/thephpleague/climate/pull/128#issuecomment-427588721

**Comment by duncan3dc** [comment]
@rvalitov What difference are you referring to? It looks the same to me [here](https://github.com/symfony/symfony/blob/5ed68eec7ea4d308970b8fd0742ea22cd12ca074/src/Symfony/Component/Console/Output/StreamOutput.php#L98)

**Comment by duncan3dc** [comment]
Merging this as the discussion seems to have been resolved on #128, thanks @azjezz!

**Pull request merged**
