### PR TITLE
Add mbstring requirement to composer.json (#109)

### PR DESCRIPTION
**Pull request by colinodell**
See issue #109

### CODE REVIEW

**Comment by jasverix** [comment]
I actually don't think packages such as this should requre extensions - because some people would rather use polyfills such as symfony/polyfill-mbstring. But maybe as a suggestion, so the message will pop up when installing this package.

**Comment by garrettw** [comment]
Maybe what composer really needs is a way to require one thing OR the other, which would also need the ability to mark one of the options as preferred, so that in the case that the user has neither, composer will know what to install.

**Comment by duncan3dc** [comment]
Doesn't `provide` already do that? Maybe it just needs extending to be able to "provide" PHP extensions. Then `symfony/polyfill` could "provide" `ext-mbstring`

**Comment by garrettw** [comment]
Actually @colinodell I'm wondering if it would be better to just require the polyfill and not the extension. That way if they have the extension it will just use that, and if not, it will use the polyfill. Seems to me that doing it that way would be best for ease of use.

**Comment by duncan3dc** [comment]
Rather than install the polyfill every time, I've added a `suggest` (a5babd16a70acbcadbefa3e28f04947a1c60a3b1). Thanks to the nice way composer works it will only suggest it if it detects `ext-mbstring` is not installed

**Pull request closed without merging**
