### PR TITLE
Create some more standard Writer classes

### PR DESCRIPTION
**Pull request by duncan3dc**
* StdErr (to go with StdOut, related to #37)
* Buffer (to stash content for using later, would help with #44 and #55)

Example usage:
```php
use League\CLImate\Util\Writer\Buffer;
use League\CLImate\Util\Output;

$buffer = new Buffer;
$climate->setOutput(new Output($buffer));

$climate->out("Don't output me");
$climate->out("Or me");

file_put_contents("/tmp/climate.log", $buffer->get());
```

Would result in `/tmp/climate.log` containing:
```
Don't output me
Or me
```

### CODE REVIEW

**Comment by duncan3dc** [comment]
Sorry, I didn't see #54, should I remove those changes from here?

**Comment by joetannenbaum** [comment]
This is great, thanks @duncan3dc. On the to do is to make it less cumbersome to actually use all of these writers, working on that soon!

**Comment by duncan3dc** [comment]
Cheers @joetannenbaum, keep up the good work. CLImate is so useful!

**Comment by joetannenbaum** [comment]
Thanks @duncan3dc! Glad you're enjoying, cheers.

**Pull request merged**
